### ISSUE TITLE
bug: We can see history with same password multiple times

### ISSUE THREAD

**Issue by SAGARSINGH-1** [Itz-Manu/vaultforge#4]
As you can see in this image we can copy same password again and again and it increase same password as a new password in the history table.

<img width="936" alt="image" src="https://github.com/Itz-Manu/vaultforge/assets/81561733/0e506bc9-0526-42da-a288-f990aa61c0c5">

**Comment by manendrav** [comment]
Thanks for informing we try to resolve it
